defaults:
  - local: ../../hpack-common.yaml
  - local: ../../hpack-relude.yaml

name: gh
version: 0.1.0.0
license: MIT
copyright: 2025 Juspay
maintainer: srid@srid.ca
author: Sridhar Ratnakumar
category: System
synopsis: Haskell bindings for gh CLI
description: A standalone library for gh CLI operations
homepage: https://github.com/juspay/vira/tree/main/packages/gh

dependencies:
  - process
  - which

library:
  source-dirs: src

executables:
  gh-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - gh
      - hspec
      - hspec-discover
