defaults:
  - local: ../../hpack-common.yaml
  - local: ../../hpack-relude.yaml

name: cachix
version: 0.1.0.0
license: MIT
copyright: 2025 Juspay
maintainer: srid@srid.ca
author: Sridhar Ratnakumar
category: System
homepage: https://github.com/juspay/vira
synopsis: Haskell bindings for Cachix binary cache
description: Haskell types and functions for working with Cachix binary cache service

extra-source-files:
  - CHANGELOG.md

dependencies:
  - process
  - template-haskell
  - which

library:
  source-dirs: src

tests:
  cachix-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - cachix
      - hspec
      - hspec-discover
